/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PlaylistPhotoService } from "../playlistPhoto.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PlaylistPhotoCreateInput } from "./PlaylistPhotoCreateInput";
import { PlaylistPhoto } from "./PlaylistPhoto";
import { PlaylistPhotoFindManyArgs } from "./PlaylistPhotoFindManyArgs";
import { PlaylistPhotoWhereUniqueInput } from "./PlaylistPhotoWhereUniqueInput";
import { PlaylistPhotoUpdateInput } from "./PlaylistPhotoUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PlaylistPhotoControllerBase {
  constructor(
    protected readonly service: PlaylistPhotoService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PlaylistPhoto })
  @nestAccessControl.UseRoles({
    resource: "PlaylistPhoto",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPlaylistPhoto(
    @common.Body() data: PlaylistPhotoCreateInput
  ): Promise<PlaylistPhoto> {
    return await this.service.createPlaylistPhoto({
      data: {
        ...data,

        playlist: data.playlist
          ? {
              connect: data.playlist,
            }
          : undefined,

        photo: data.photo
          ? {
              connect: data.photo,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,

        playlist: {
          select: {
            id: true,
          },
        },

        photo: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [PlaylistPhoto] })
  @ApiNestedQuery(PlaylistPhotoFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PlaylistPhoto",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async playlistPhotos(
    @common.Req() request: Request
  ): Promise<PlaylistPhoto[]> {
    const args = plainToClass(PlaylistPhotoFindManyArgs, request.query);
    return this.service.playlistPhotos({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,

        playlist: {
          select: {
            id: true,
          },
        },

        photo: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PlaylistPhoto })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PlaylistPhoto",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async playlistPhoto(
    @common.Param() params: PlaylistPhotoWhereUniqueInput
  ): Promise<PlaylistPhoto | null> {
    const result = await this.service.playlistPhoto({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,

        playlist: {
          select: {
            id: true,
          },
        },

        photo: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PlaylistPhoto })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PlaylistPhoto",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePlaylistPhoto(
    @common.Param() params: PlaylistPhotoWhereUniqueInput,
    @common.Body() data: PlaylistPhotoUpdateInput
  ): Promise<PlaylistPhoto | null> {
    try {
      return await this.service.updatePlaylistPhoto({
        where: params,
        data: {
          ...data,

          playlist: data.playlist
            ? {
                connect: data.playlist,
              }
            : undefined,

          photo: data.photo
            ? {
                connect: data.photo,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,

          playlist: {
            select: {
              id: true,
            },
          },

          photo: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PlaylistPhoto })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PlaylistPhoto",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePlaylistPhoto(
    @common.Param() params: PlaylistPhotoWhereUniqueInput
  ): Promise<PlaylistPhoto | null> {
    try {
      return await this.service.deletePlaylistPhoto({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,

          playlist: {
            select: {
              id: true,
            },
          },

          photo: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
