/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AlbumPhotoService } from "../albumPhoto.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AlbumPhotoCreateInput } from "./AlbumPhotoCreateInput";
import { AlbumPhoto } from "./AlbumPhoto";
import { AlbumPhotoFindManyArgs } from "./AlbumPhotoFindManyArgs";
import { AlbumPhotoWhereUniqueInput } from "./AlbumPhotoWhereUniqueInput";
import { AlbumPhotoUpdateInput } from "./AlbumPhotoUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AlbumPhotoControllerBase {
  constructor(
    protected readonly service: AlbumPhotoService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AlbumPhoto })
  @nestAccessControl.UseRoles({
    resource: "AlbumPhoto",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createAlbumPhoto(
    @common.Body() data: AlbumPhotoCreateInput
  ): Promise<AlbumPhoto> {
    return await this.service.createAlbumPhoto({
      data: {
        ...data,

        album: data.album
          ? {
              connect: data.album,
            }
          : undefined,

        photo: data.photo
          ? {
              connect: data.photo,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,

        album: {
          select: {
            id: true,
          },
        },

        photo: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [AlbumPhoto] })
  @ApiNestedQuery(AlbumPhotoFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AlbumPhoto",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async albumPhotos(@common.Req() request: Request): Promise<AlbumPhoto[]> {
    const args = plainToClass(AlbumPhotoFindManyArgs, request.query);
    return this.service.albumPhotos({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,

        album: {
          select: {
            id: true,
          },
        },

        photo: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AlbumPhoto })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AlbumPhoto",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async albumPhoto(
    @common.Param() params: AlbumPhotoWhereUniqueInput
  ): Promise<AlbumPhoto | null> {
    const result = await this.service.albumPhoto({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,

        album: {
          select: {
            id: true,
          },
        },

        photo: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AlbumPhoto })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AlbumPhoto",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateAlbumPhoto(
    @common.Param() params: AlbumPhotoWhereUniqueInput,
    @common.Body() data: AlbumPhotoUpdateInput
  ): Promise<AlbumPhoto | null> {
    try {
      return await this.service.updateAlbumPhoto({
        where: params,
        data: {
          ...data,

          album: data.album
            ? {
                connect: data.album,
              }
            : undefined,

          photo: data.photo
            ? {
                connect: data.photo,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,

          album: {
            select: {
              id: true,
            },
          },

          photo: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AlbumPhoto })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AlbumPhoto",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteAlbumPhoto(
    @common.Param() params: AlbumPhotoWhereUniqueInput
  ): Promise<AlbumPhoto | null> {
    try {
      return await this.service.deleteAlbumPhoto({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,

          album: {
            select: {
              id: true,
            },
          },

          photo: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
