/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { GraphQLUpload } from "graphql-upload";
import { FileUpload } from "src/storage/base/storage.types";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Album } from "./Album";
import { AlbumCountArgs } from "./AlbumCountArgs";
import { AlbumFindManyArgs } from "./AlbumFindManyArgs";
import { AlbumFindUniqueArgs } from "./AlbumFindUniqueArgs";
import { CreateAlbumArgs } from "./CreateAlbumArgs";
import { UpdateAlbumArgs } from "./UpdateAlbumArgs";
import { DeleteAlbumArgs } from "./DeleteAlbumArgs";
import { UserAlbumFindManyArgs } from "../../userAlbum/base/UserAlbumFindManyArgs";
import { UserAlbum } from "../../userAlbum/base/UserAlbum";
import { AlbumPhotoFindManyArgs } from "../../albumPhoto/base/AlbumPhotoFindManyArgs";
import { AlbumPhoto } from "../../albumPhoto/base/AlbumPhoto";
import { AlbumService } from "../album.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Album)
export class AlbumResolverBase {
  constructor(
    protected readonly service: AlbumService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Album",
    action: "read",
    possession: "any",
  })
  async _albumsMeta(
    @graphql.Args() args: AlbumCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Album])
  @nestAccessControl.UseRoles({
    resource: "Album",
    action: "read",
    possession: "any",
  })
  async albums(@graphql.Args() args: AlbumFindManyArgs): Promise<Album[]> {
    return this.service.albums(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Album, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Album",
    action: "read",
    possession: "own",
  })
  async album(
    @graphql.Args() args: AlbumFindUniqueArgs
  ): Promise<Album | null> {
    const result = await this.service.album(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Album)
  @nestAccessControl.UseRoles({
    resource: "Album",
    action: "create",
    possession: "any",
  })
  async createAlbum(@graphql.Args() args: CreateAlbumArgs): Promise<Album> {
    return await this.service.createAlbum({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Album)
  @nestAccessControl.UseRoles({
    resource: "Album",
    action: "update",
    possession: "any",
  })
  async updateAlbum(
    @graphql.Args() args: UpdateAlbumArgs
  ): Promise<Album | null> {
    try {
      return await this.service.updateAlbum({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Album)
  @nestAccessControl.UseRoles({
    resource: "Album",
    action: "delete",
    possession: "any",
  })
  async deleteAlbum(
    @graphql.Args() args: DeleteAlbumArgs
  ): Promise<Album | null> {
    try {
      return await this.service.deleteAlbum(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Album)
  async uploadCoverPhoto(
    @graphql.Args({
      name: "file",
      type: () => GraphQLUpload,
    })
    file: FileUpload,
    @graphql.Args()
    args: AlbumFindUniqueArgs
  ): Promise<Album> {
    return await this.service.uploadCoverPhoto(args, file);
  }

  @graphql.Mutation(() => Album)
  async deleteCoverPhoto(
    @graphql.Args()
    args: AlbumFindUniqueArgs
  ): Promise<Album> {
    return await this.service.deleteCoverPhoto(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [UserAlbum], { name: "userAlbums" })
  @nestAccessControl.UseRoles({
    resource: "UserAlbum",
    action: "read",
    possession: "any",
  })
  async findUserAlbums(
    @graphql.Parent() parent: Album,
    @graphql.Args() args: UserAlbumFindManyArgs
  ): Promise<UserAlbum[]> {
    const results = await this.service.findUserAlbums(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [AlbumPhoto], { name: "albumPhotos" })
  @nestAccessControl.UseRoles({
    resource: "AlbumPhoto",
    action: "read",
    possession: "any",
  })
  async findAlbumPhotos(
    @graphql.Parent() parent: Album,
    @graphql.Args() args: AlbumPhotoFindManyArgs
  ): Promise<AlbumPhoto[]> {
    const results = await this.service.findAlbumPhotos(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
