/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PhotoService } from "../photo.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PhotoCreateInput } from "./PhotoCreateInput";
import { Photo } from "./Photo";
import { PhotoFindManyArgs } from "./PhotoFindManyArgs";
import { PhotoWhereUniqueInput } from "./PhotoWhereUniqueInput";
import { PhotoUpdateInput } from "./PhotoUpdateInput";
import { AlbumPhotoFindManyArgs } from "../../albumPhoto/base/AlbumPhotoFindManyArgs";
import { AlbumPhoto } from "../../albumPhoto/base/AlbumPhoto";
import { AlbumPhotoWhereUniqueInput } from "../../albumPhoto/base/AlbumPhotoWhereUniqueInput";
import { PlaylistPhotoFindManyArgs } from "../../playlistPhoto/base/PlaylistPhotoFindManyArgs";
import { PlaylistPhoto } from "../../playlistPhoto/base/PlaylistPhoto";
import { PlaylistPhotoWhereUniqueInput } from "../../playlistPhoto/base/PlaylistPhotoWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PhotoControllerBase {
  constructor(
    protected readonly service: PhotoService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Photo })
  @nestAccessControl.UseRoles({
    resource: "Photo",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPhoto(@common.Body() data: PhotoCreateInput): Promise<Photo> {
    return await this.service.createPhoto({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        url: true,
        title: true,
        description: true,
        uploadedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Photo] })
  @ApiNestedQuery(PhotoFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Photo",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async photos(@common.Req() request: Request): Promise<Photo[]> {
    const args = plainToClass(PhotoFindManyArgs, request.query);
    return this.service.photos({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        url: true,
        title: true,
        description: true,
        uploadedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Photo })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Photo",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async photo(
    @common.Param() params: PhotoWhereUniqueInput
  ): Promise<Photo | null> {
    const result = await this.service.photo({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        url: true,
        title: true,
        description: true,
        uploadedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Photo })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Photo",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePhoto(
    @common.Param() params: PhotoWhereUniqueInput,
    @common.Body() data: PhotoUpdateInput
  ): Promise<Photo | null> {
    try {
      return await this.service.updatePhoto({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          url: true,
          title: true,
          description: true,
          uploadedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Photo })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Photo",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePhoto(
    @common.Param() params: PhotoWhereUniqueInput
  ): Promise<Photo | null> {
    try {
      return await this.service.deletePhoto({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          url: true,
          title: true,
          description: true,
          uploadedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/albumPhotos")
  @ApiNestedQuery(AlbumPhotoFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AlbumPhoto",
    action: "read",
    possession: "any",
  })
  async findAlbumPhotos(
    @common.Req() request: Request,
    @common.Param() params: PhotoWhereUniqueInput
  ): Promise<AlbumPhoto[]> {
    const query = plainToClass(AlbumPhotoFindManyArgs, request.query);
    const results = await this.service.findAlbumPhotos(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,

        album: {
          select: {
            id: true,
          },
        },

        photo: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/albumPhotos")
  @nestAccessControl.UseRoles({
    resource: "Photo",
    action: "update",
    possession: "any",
  })
  async connectAlbumPhotos(
    @common.Param() params: PhotoWhereUniqueInput,
    @common.Body() body: AlbumPhotoWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      albumPhotos: {
        connect: body,
      },
    };
    await this.service.updatePhoto({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/albumPhotos")
  @nestAccessControl.UseRoles({
    resource: "Photo",
    action: "update",
    possession: "any",
  })
  async updateAlbumPhotos(
    @common.Param() params: PhotoWhereUniqueInput,
    @common.Body() body: AlbumPhotoWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      albumPhotos: {
        set: body,
      },
    };
    await this.service.updatePhoto({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/albumPhotos")
  @nestAccessControl.UseRoles({
    resource: "Photo",
    action: "update",
    possession: "any",
  })
  async disconnectAlbumPhotos(
    @common.Param() params: PhotoWhereUniqueInput,
    @common.Body() body: AlbumPhotoWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      albumPhotos: {
        disconnect: body,
      },
    };
    await this.service.updatePhoto({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/playlistPhotos")
  @ApiNestedQuery(PlaylistPhotoFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PlaylistPhoto",
    action: "read",
    possession: "any",
  })
  async findPlaylistPhotos(
    @common.Req() request: Request,
    @common.Param() params: PhotoWhereUniqueInput
  ): Promise<PlaylistPhoto[]> {
    const query = plainToClass(PlaylistPhotoFindManyArgs, request.query);
    const results = await this.service.findPlaylistPhotos(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,

        playlist: {
          select: {
            id: true,
          },
        },

        photo: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/playlistPhotos")
  @nestAccessControl.UseRoles({
    resource: "Photo",
    action: "update",
    possession: "any",
  })
  async connectPlaylistPhotos(
    @common.Param() params: PhotoWhereUniqueInput,
    @common.Body() body: PlaylistPhotoWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      playlistPhotos: {
        connect: body,
      },
    };
    await this.service.updatePhoto({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/playlistPhotos")
  @nestAccessControl.UseRoles({
    resource: "Photo",
    action: "update",
    possession: "any",
  })
  async updatePlaylistPhotos(
    @common.Param() params: PhotoWhereUniqueInput,
    @common.Body() body: PlaylistPhotoWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      playlistPhotos: {
        set: body,
      },
    };
    await this.service.updatePhoto({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/playlistPhotos")
  @nestAccessControl.UseRoles({
    resource: "Photo",
    action: "update",
    possession: "any",
  })
  async disconnectPlaylistPhotos(
    @common.Param() params: PhotoWhereUniqueInput,
    @common.Body() body: PlaylistPhotoWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      playlistPhotos: {
        disconnect: body,
      },
    };
    await this.service.updatePhoto({
      where: params,
      data,
      select: { id: true },
    });
  }
}
